---
- name: all host included
  hosts: my

  tasks:
  - name: create a group
    group: name=india state=present
  - name: create a user
    user: name=yogesh groups=india state=present 
  - name: create a directory
    file: path=/var/tmp/demo state=directory
  - name: create a file inside directory
    file: path=/var/tmp/demo/ name=demotest state=touch
  - name: copy log files to /var/tmp/demo
    copy: src=/var/log/messages dest=/var/tmp/demo/
  - name: intall ntp app
    yum : name=ntp state=present
  - name: remove all line in ntp.conf
    lineinfile: path=/etc/ntp.conf backup=yes regexp="." state=absent
  - name: add ntp servers in ntp.conf file
    lineinfile: path=/etc/ntp.conf  line='server0.centos.pool.ntp.org iburst'
  - name: add ntp servers in ntp.conf file2
    lineinfile: path=/etc/ntp.conf  line='server2.centos.pool.ntp.org iburst'
    notify:
      restart ntp
    register: out
  - name: debug outpu
    debug: var=out
  
  handlers:
  - name: restart ntp
    service: name=ntpd state=restarted   
