---
# tasks file for java
- name: Download java tar
  get_url:
    url:  {{ jdk_url }} 
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
    dest: /tmp
    mode: 0777

- name: extract to /opt
  
